### ISSUE TITLE
Bug in cache feature

### ISSUE THREAD

**Issue by MFlisar** [dkunzler/esperandro#37]
If I use setter with return type, the cache code is generated after returning the result of the setter...

Generated code looks like following:

    @Override
    public boolean versionShown(int versionShown) {
        return preferences.edit().putInt("versionShown", versionShown).commit();
        cache.remove("versionShown");
    }

and should look like following:

    @Override
    public boolean versionShown(int versionShown) {
        cache.remove("versionShown");
        return preferences.edit().putInt("versionShown", versionShown).commit();
    }

Same bug if I use the cache with `cacheOnPut = true`...

**Comment by dkunzler** [comment]
Thanks, I will fix this asap!

**Comment by dkunzler** [comment]
just release the fixed version 2.3.1
should be synced in a few hours to central.

sorry for the delay, I was about to try some other things.

I will not update the documentation regarding caching since I want to make this an external module to the processor to make sure that only developers are using it that read the documentation on this.
