### ISSUE TITLE
Problem when using in combination with PreferenceFragments

### ISSUE THREAD

**Issue by MFlisar** [dkunzler/esperandro#43]
I have a simple class like following (minimal extract of my file) using v2.4.1:

	@Cached(cacheOnPut = true, support = true)
	@SharedPreferences(name = PrefManager.PREF_NAME, mode = SharedPreferenceMode.PRIVATE)
	public interface PrefManager extends SharedPreferenceActions, CacheActions
	{
		String PREF_NAME = "mainPrefs";
		
		// a lot of default preferences, ALL have a default value
		// Example:
		@Default(ofInt = 0)
		int versionShown();
		void versionShown(int versionShown);
		
		// some custom serialised values without default value
		DataManager.ExistingDataSources existingDataSources();
		void existingDataSources(DataManager.ExistingDataSources existingDataSources);
	}

**What I do**

1. on my first app start, I check a preference with default value and if it is the first app start, I manually initialise my preferences without default value (my custom serialisable fields) and make sure to set all default values and persist them
2. I use Esperandro everyhwere in my app and it works fine
3. additional, I use the same preference file in my `PreferenceFragments`

**Problem**

Sometimes after I return from my `SettingsActivity ` the preferences are completely resetted. I'm sure I'm using esperandro anywhere in my code and that only the `PreferenceFragment`s directly manipulate the preference file. Any ideas how this can happen? Do you see a problem in my code?

**CODE**

*My initialisation function*

    public static void initPrefs()
    {
        if (MainApp.getPrefs().existingDataSources() == null)
            MainApp.getPrefs().existingDataSources(new DataManager.ExistingDataSources());
        int versionShown = MainApp.getPrefs().versionShown();
        if (versionShown == 0)
        {
            MainApp.getPrefs().initDefaults();
            // force saving all prefs to the file, we need this so that the PreferenceFragments work correctly
            MainApp.getPrefs().get().edit().commit();
        }
    }

*My settings activity*

	public class SettingsActivity extends AppCompatActivity
	{
		@Override
		public void onDestroy()
		{
			// reset all cached values in esperandro, we may have changed them without using esperandro!!!
			MainApp.getPrefs().resetCache();
			super.onDestroy();
		}
	}

*My base `PreferenceFragment`, a minimal version*

	public abstract class BasePrefFragment extends PreferenceFragmentCompat
	{
		@Override
		public void onCreatePreferences(Bundle bundle, String s) {
                        // ATTENTION: we use the same pref file as esperandro!
			getPreferenceManager().setSharedPreferencesName(PrefManager.PREF_NAME);
			addPreferencesFromResource(getPreferenceId());
		}

		public abstract int getPreferenceId();
	}

**Comment by dkunzler** [comment]
Hi,
I have no idea therefore some questions out of the blue.
- Can you reproduce this reliably? If you use an older version of esperandro, can you verify with certain that you don't have this error with the older version?
- Can you check if this also occurs if you have no `@Cached` annotation?
- Can you check if you have a `clear` command anywhere in your code, either on the esperandro object or on the android SharedPreferences object?
- Do you have other threads than the main thread that read or write preferences?

At the moment I don't see anything that could cause this in the generated code. I don't know if some awkward multi-threaded order of calls to the editor could cause this.

I see that you always initiliaze the defaults since you don't increment your versionShown, but initDefaults should be idempotent.

One thing to test: You could change the void setters to boolean setter to make sure that commit instead of apply is called. It the error doesn't occur after this I'm sure it is a threading problem of some kind. (perhaps one that could be resolved in esperandro)

**Comment by MFlisar** [comment]
I'm setting the `versionShown`variable somewhere else, I'm doing a few things at the first start (importing data, setting preferences, showing intro) and afterwards set the variable, so that is fine. It works, as all this is only called once, as long as I don't open my `SettingsActivity`.

Sadly, I can't reproduce it currently reliably... But thanks for the feedback, I'll check what you suggested (again)...

**Comment by dkunzler** [comment]
Reproducability is always the problem with these nasty bugs. At least this is a hint that it has remotely something to to with threading or non-deterministic order of execution.
I would start with setters with boolean return type to make sure that esperandro really saves the file before returning the method.

**Comment by MFlisar** [comment]
Actually, I think I have it... I used a reflection method to reset the cache and after you've added the function to reset the cache, I removed my reflection method and replaced it with the available reset function... And here is the problem, I used `clear()` instead of `resetCache()`...

Searching for clear in my preference package immediately showed me that. I searched for the problem yesterday already and I'm totally sure, I checked if I have replaced all my old reflection function calls with the correct one, but still I've overseen one.

I think that's the complete problem, so thanks for your input and feedback.
